language: node_js
node_js:
  - "6.1"
branches:
  only:
    - development
install:
  - npm --prefix ./projekt/desktop-app install ./projekt/desktop-app
  - npm --prefix ./projekt/node-api install ./projekt/node-api
before_script:
  - npm install -g bower
  - bower install
  - npm install -g nodemon
  - nodemon projekt/node-api/
script:
  - npm --prefix ./projekt/desktop-app test